### ISSUE TITLE
jsonpackage.py and jsonpackage2.py - json.dumps() TypeError

### ISSUE THREAD

**Issue by ss-is-master-chief** [ss-is-master-chief/spatial_support#2]
Code: https://github.com/ss-is-master-chief/spatial_support/blob/master/jsonpackage.py

Running `jsonpackage.py` give te following error

```
python jsonpackage.py
stands_1929_30.shp ------- stands_1929_30
stands_1908_9.shp ------- stands_1908_9
silviculture_treatments.shp ------- silviculture_treatments
stands_1912_13.shp ------- stands_1912_13
stands_1947.shp ------- stands_1947
soils.shp ------- soils
stands_1986_93.shp ------- stands_1986_93
hf_gates_smeyer_m.shp ------- hf_gates_smeyer_m
stands_1956.shp ------- stands_1956
linear_features.shp ------- linear_features
1938_hurricane_damage.shp ------- 1938_hurricane_damage
stands_1919.shp ------- stands_1919
silviculture_treatments_08_21_2010.shp ------- silviculture_treatments_08_21_2010
tracts.shp ------- tracts
compartments.shp ------- compartments
stands_1937.shp ------- stands_1937
stands_1923.shp ------- stands_1923
ph_landuse_history.shp ------- ph_landuse_history
ph_historical_features.shp ------- ph_historical_features
ph_natural_disturbance2.shp ------- ph_natural_disturbance2
ph_ag_abandonment.shp ------- ph_ag_abandonment
ph_ownership_history.shp ------- ph_ownership_history
ph_archive_agricultural_references.shp ------- ph_archive_agricultural_references
Traceback (most recent call last):
  File "jsonpackage.py", line 202, in <module>
    create_datapackage()
  File "jsonpackage.py", line 196, in create_datapackage
    separators=(',', ': '))
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 3 keyword-only arguments) were given
```

@henrykironde Please have a look

**Comment by ss-is-master-chief** [comment]
@henrykironde Removing `output_spec_datapack` as one of the parameters in line 203 i.e `json.dumps()` successfully creates the necessary files

**Comment by henrykironde** [comment]
Am closing this because we solved it for now
